load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "queue",
    srcs = [
        "runner.go",
        "stage.go",
        "store.go",
    ],
    importpath = "github.com/iampat/benchmarks/scaling-queue-postgres/internal/queue",
    visibility = ["//scaling-queue-postgres:__subpackages__"],
    deps = [
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@org_golang_x_time//rate",
    ],
)

go_test(
    name = "queue_test",
    srcs = [
        "integration_test.go",
        "runner_test.go",
        "stage_test.go",
        "store_test.go",
    ],
    deps = [
        ":queue",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@org_golang_x_time//rate",
    ],
)
