load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "report_lib",
    srcs = ["main.go"],
    importpath = "github.com/iampat/benchmarks/scaling-queue-postgres/cmd/report",
    visibility = ["//visibility:private"],
    deps = ["//scaling-queue-postgres/internal/benchreport"],
)

go_binary(
    name = "report",
    embed = [":report_lib"],
    visibility = ["//visibility:public"],
)
