load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "experiment",
    srcs = ["experiment.go"],
    importpath = "github.com/iampat/benchmarks/scaling-queue-postgres/internal/experiment",
    visibility = ["//scaling-queue-postgres:__subpackages__"],
)

go_test(
    name = "experiment_test",
    srcs = ["experiment_test.go"],
    deps = [
        ":experiment",
        "//scaling-queue-postgres/internal/queue",
    ],
)
